In [5]:
import pandas as pd
import numpy as np
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
books = pd.read_csv("Books.csv", low_memory=False)

print(books.shape)
books.head()

(271360, 8)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [14]:
print(books.columns.tolist())

['Book-Title', 'Book-Author']

In [13]:
books = books[['Book-Title', 'Book-Author']]

books.dropna(inplace=True)

books.head()

C:\Users\sanju\AppData\Local\Temp\ipykernel_8928\2736469609.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books.dropna(inplace=True)

                                          Book-Title           Book-Author
0                                Classical Mythology    Mark P. O. Morford
1                                       Clara Callan  Richard Bruce Wright
2                               Decision in Normandy          Carlo D'Este
3  Flu: The Story of the Great Influenza Pandemic...      Gina Bari Kolata
4                             The Mummies of Urumchi       E. J. W. Barber

In [12]:
books['features'] = (
    books['Book-Title'].astype(str) +
    " " +
    books['Book-Author'].astype(str)
)

books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,features
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,Classical Mythology Mark P. O. Morford
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,Clara Callan Richard Bruce Wright
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,Decision in Normandy Carlo D'Este
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,Flu: The Story of the Great Influenza Pandemic...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,The Mummies of Urumchi E. J. W. Barber

In [26]:
books['features'] = books.iloc[:, 0].astype(str) + " " + books.iloc[:, 1].astype(str)

tfidf = TfidfVectorizer(stop_words='english')

vectors = tfidf.fit_transform(books['features'])

print(vectors.shape)

C:\Users\sanju\AppData\Local\Temp\ipykernel_8928\449753021.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['features'] = books.iloc[:, 0].astype(str) + " " + books.iloc[:, 1].astype(str)

(271358, 113556)

In [31]:
print(type(vectors))
print(vectors.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(271358, 113556)

In [9]:
def recommend(book_name):

    book_name = book_name.lower()

    matches = books[
        books['Book-Title'].str.lower() == book_name
    ]

    if matches.empty:
        print("Book not found")
        return

    idx = matches.index[0]

    distances = similarity[idx]

    book_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    for i in book_list:
        print(books.iloc[i[0]]['Book-Title'])

In [32]:
print(books.iloc[:20, 0])

0                                   Classical Mythology
1                                          Clara Callan
2                                  Decision in Normandy
3     Flu: The Story of the Great Influenza Pandemic...
4                                The Mummies of Urumchi
5                                The Kitchen God's Wife
6     What If?: The World's Foremost Military Histor...
7                                       PLEADING GUILTY
8     Under the Black Flag: The Romance and the Real...
9               Where You'll Find Me: And Other Stories
10                          Nights Below Station Street
11    Hitler's Secret Bankers: The Myth of Swiss Neu...
12                                   The Middle Stories
13                                             Jane Doe
14    A Second Chicken Soup for the Woman's Soul (Ch...
15         The Witchfinder (Amos Walker Mystery Series)
16    More Cunning Than Man: A Social History of Rat...
17                        Goodbye to the Buttermilk Sky
18                                        The Testament
19                 Beloved (Plume Contemporary Fiction)
Name: Book-Title, dtype: object

In [ ]:
print(type(vectors))
print(vectors.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(271358, 113556)

In [33]:
import pickle

# Save only books dataframe
pickle.dump(books, open("books.pkl", "wb"))

print("books.pkl created successfully")

books.pkl created successfully

In [6]:
import os

print(os.path.exists("books.pkl"))
print(os.path.exists("similarity.pkl"))

False
False